apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-apl
  namespace: reverse-proxy
spec:
  type: NodePort
  selector:
    app: reverse-proxy-apl
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30000 # 30000-32767でなければならない
