apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reverse-proxy

configMapGenerator:
- name: default.conf
  files:
  - config/default.conf

images:
- name: nginx
  newTag: latest

resources:
- secret/reverse-proxy-certificate.yaml
- nginx-deployment.yaml
- nginx-service.yaml
