apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-nginx
  namespace: reverse-proxy
spec:
  selector:
    matchLabels:
      app: reverse-proxy-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: reverse-proxy-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          readOnly: true
          name: reverse-proxy-nginx-conf
        - mountPath: /etc/nginx/ssl/
          readOnly: true
          name: reverse-proxy-certificate-conf
      volumes:
      - name: reverse-proxy-nginx-conf
        configMap:
          name: default.conf
          items:
          - key: default.conf
            path: default.conf
      - name: reverse-proxy-certificate-conf
        secret:
          secretName: reverse-proxy-certificate
          items:
          - key: root.crt
            path: root.crt
          - key: server.crt
            path: server.crt
          - key: server.key
            path: server.key
          - key: server.password
            path: server.password
