apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-nginx
  namespace: reverse-proxy
spec:
  type: NodePort
  selector:
    app: reverse-proxy-nginx
  ports:
  - port: 30080
    targetPort: 30080
    protocol: TCP
    nodePort: 30080
