apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-nginx
  namespace: reverse-proxy
spec:
  selector:
    matchLabels:
      app: reverse-proxy-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: reverse-proxy-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 443
