apiVersion: v1
kind: Service
metadata:
  name: spanner-emulator
  namespace: reverse-proxy
spec:
  selector:
    app: spanner-emulator
  ports:
  - name: spanner-cli
    port: 9010
    targetPort: 9010
  - name: grpc
    port: 9020
    targetPort: 9020
